### ISSUE TITLE
Problem downloading volumes

### ISSUE THREAD

**Issue by DarioMarimon** [1s0n/Mangareader-Downloader-v2#2] opened 2023-06-20 22:03 UTC
Hi! First of all, I've been reading your code, and nice work :) It works great with chapters, I've downloaded some thanks to you!

But in volumes (at least using the link "https://mangareader.to/read/land-of-the-lustrous-28/ja/volume-1") it gets stuck on third page:
![image](https://github.com/1s0n/Mangareader-Downloader-v2/assets/104064692/572589b8-e971-47c9-811a-b7bdd4cebe0c)

Maybe on a day off ill try looking for the cause, if I find it i'll make a branch with the fix.

Anyway, thanks again for your work, I'll look forward to it!

**Comment by 1s0n** [comment] 2023-06-21 02:05
Hi, I do recognise this issue, as its quite common when I download manga from different series. This is caused by this method of me verifying image endings to pick out images that have not finished loading, it seems like there's not much documentation surrounding these image endings, so I'll just have to add them as new ones pop up.

I'll let you know when I fix it.

**Comment by 1s0n** [comment] 2023-06-21 02:48
Should be fixed now.

**Closed as completed** 2023-12-13 23:27 UTC
